# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06ae3990bb847e8efca5d721880e513d56a5880413649da672853d9ff4dd74ecdba9c5ae24870390f06bf0fa9faf4c85dd1c342bd4165bffee333fdae90ae648

test:
  secret_key_base: 9759bad9b252d499e5b167170b0c499a59b6aa2c3b343a13ba1508f694263336b94d58b7f4769f0ea0c4070926291fafd7188d31fdcdab5861ad8366e81f90a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
